dist: trusty
sudo: require
notifications: 
  email: false

addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - g++-8

before_install:
  - export CC=/usr/bin/gcc-8
  - export CXX=/usr/bin/g++-8

language: cpp
compiler: gcc

script:
    - mkdir build && cd build
    - cmake .. && make

after_success:
    - $TRAVIS_BUILD_DIR/build/bin/tests