dist: trusty
sudo: require

before_install:
  - sudo apt-get install ncurses-dev
  - sudo apt-get install ncurses
  

language: cpp
compiler: gcc

script:
    - export CC=/usr/bin/gcc-7
    - export CXX=/usr/bin/g++-7
    - gcc -v && g++ -v && cmake --version
    - mkdir build
    - cd build
    - cmake .. && make