dist: trusty
sudo: require
notifications: 
  email: false

language: cpp
compiler: 
  - gcc
  - clang

matrix:
  include:
    - os: linux
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-8
      env:
        - MATRIX_EVAL="CC=gcc-8 && CXX=g++-8"
    - os: linux
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
            - llvm-toolchain-trusty-6.0
          packages:
            - clang-6.0
      env:
        - MATRIX_EVAL="CC=clang-6.0 && CXX=clang++-6.0"

before_install:
  - eval "${MATRIX_EVAL}"
  - $CC --version && $CXX --version

script:
    - mkdir build && cd build
    - cmake .. && make

after_success:
    - $TRAVIS_BUILD_DIR/build/bin/tests