dist: trusty
sudo: require

matrix:
  include:
    - os: linux
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-8
      env:
        - MATRIX_EVAL="CC=/usr/bin/gcc-8 && CXX=/usr/bin/g++-8"

before_install:
  - eval "${MATRIX_EVAL}"
  - sudo apt-get install libncurses5
  - sudo apt-get install libncurses5-dev

language: cpp
compiler: gcc

script:
    - gcc -v && g++ -v && cmake --version
    - mkdir build
    - cd build
    - cmake .. && make
